---
title: "test"
output: html_document
date: "2024-11-21"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

tavern_adj <- c("Stout", "Bloody", "Slow", "Dull", "Soaked", "Drunken",
            "Crooked", "Dark", "Fabulous", "Noble", "Soft", "Red",
            "Green", "Whtie", "Black", "Yellow", "Blue", "Burning",
            "Broken", "Shattered", "Mighty", "Strong", "Lonely",
            "Poor", "Old", "Generous", "Lanky", "Hapless", "Tall",
            "Remarkable", "Frugal", "Prudent", "Foul", "Evil", "Good",
            "Rotten", "Shining", "Fragile", "Hungry", "Tired",
            "Patient", "Merciful", "Immortal", "Faithful", "Friendly",
            "Forlorn", "Adoring", "Brittle", "Floating", "Sharp",
            "Worn", "Cursed", "Beautiful", "Beleoved", "Quiet",
            "Happy", "Courageous", "Wounded", "Blind", "Clairvoyant",
            "Blushing", "Calm", "Wary", "Cheerful", "Wise", "Clumsy",
            "Boorish", "Boastful", "Sly", "Daring", "Rebellious",
            "Diligent", "Disguised", "Ominous", "Determined", "Reliable",
            "Loyal", "Raging", "Excited", "Shy", "Magical", "Trecherous",
            "False", "Foolhardy", "Golden", "Frozen", "Gracious", "Hairy",
            "Hidden", "Hoarse", "Honest", "Humble", "Limping",
            "Lively", "Lucky", "Lean", "Nefarious", "Ogling",
            "Subtle", "Crazy")

tavern_noun <- c("Rooster", "Raven", "Crow", "Toad", "Hound", "Fox",
                 "Bull", "Boar", "Clam", "Hawk", "Eagle", "Mouse",
                 "Rat", "Frog", "Elk", "Cat", "Guardian", "Hunter",
                 "Barbarian", "Witch", "Troll", "Sword", "Shield",
                 "Bow", "Dagger", "Hammer", "Helm", "Acrobat", "Lion",
                 "Ghoul", "Druid", "Master", "King", "Queen", "Prince",
                 "Princess", "Shrub", "Tree", "Bear", "Smile", "Eye",
                 "Tounge", "Flounder", "Whale", "Steer", "Stallion",
                 "Mare", "Wish", "Hoof", "Goat", "Tower", "Fist",
                 "Monk", "Sleep", "Fool", "Knight", "Poet", "Thrush",
                 "Diamond", "Ruby", "Emerald", "Lute", "Drum", "Flute",
                 "Farmer", "Songbird", "Mother", "Father", "Solider",
                 "Sailor", "Brewer", "Hornet", "Donkey", "Hare",
                 "Twig", "Barrel", "Boot", "Fang", "Skull", "Snail",
                 "Beetle")

tavern <- paste("The", sample(tavern_adj, 1), sample(tavern_noun, 1))

print(tavern)

```

```{r}

#d20
sample(1:20, 1)

#d12
sample(1:12, 1)

#d10
sample(1:10, 1)

#d8
sample(1:8, 1)

#d6
sample(1:6, 1)

#d4
sample(1:4, 1)

#d100
sample(1:100, 1)

mult_dice <- function(dice_type, dice_quant){
  rolls <- c(sample(1:dice_type, dice_quant, replace = TRUE))
  sum_rolls <- sum(rolls)
  return(list(rolls = rolls, sum = sum_rolls))
}

mult_dice(4, 2)

```

```{r}

#NPC stat generator 

stat_gen <- function() {
  stat <- c(sample(1:6, 4, replace = TRUE))
  stat <- stat[stat != min(stat)]
  sum(stat)
}

for(i in 1:6) {
  temp <- paste0("stat", i)
  
  assign(temp, stat_gen())
}

npc <- paste("Strength:", stat1,
      "Dexterity:", stat2,
      "Constitution:", stat3,
      "Intelligence:", stat4,
      "Wisdom:", stat5,
      "Charisma:", stat6, sep = "\n")

cat(npc, sep="\n")

```

```{r}
## Difficulty Class


difficulty_check <- function(dc, mod=0){
  roll <- sample(1:20, 1)
  if((roll + mod) >= dc){
    paste("Roll:", roll, "+ Modifer:", mod, "=", (roll + mod), "...Success!")
  } 
  else {
    paste("Roll:", roll, "+ Modifer:", mod, "=", (roll + mod), "...Failure")
  }
}

difficulty_check(18, 8)

```
